[project]
name = "cta-orange"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cta-kernel==0.1.0",
]

[dependency-groups]
dev = [
    "anyqt==0.2.1",
    "numpy==2.4.2",
    "orange3==3.39.0",
    "orange3-textable==3.2.7",
    "pyqt6>=6.11.0",
    "pyqt6-webengine>=6.11.0",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
    "setuptools==65.5.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

